### ISSUE TITLE
Plugin does not enable

### ISSUE THREAD

**Issue by AmareseV1** [NoahvdAa/HealthHider#2]
Spigot: GuardSpigot 1.19.2
Error: [22:12:46 INFO]: [HealthHider] Enabling HealthHider v1.0.1
[22:12:46 ERROR]: Error occurred while enabling HealthHider v1.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/core/registries/BuiltInRegistries
        at me.noahvdaa.healthhider.HealthHider.loadConfig(HealthHider.java:58) ~[HealthHider-1.0.1.jar:?]
        at me.noahvdaa.healthhider.HealthHider.onEnable(HealthHider.java:27) ~[HealthHider-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(:1015) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(:978) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:544) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-"3700d69"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.registries.BuiltInRegistries
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 18 more
[22:12:46 INFO]: [HealthHider] Disabling HealthHider v1.0.1

**Comment by NoahvdAa** [comment]
HealthHider was made for 1.19.3 and will soon work on 1.19.4, 1.19.2 and below aren't supported.
